---
title: elianelemieux.ca
timezone: America/New_York
collections:
  massages:
    title: Massages
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
  source_dir: _sass
