---
title: Éliane Lemieux - Masso-kinésithérapeute et herboriste-naturopathe
timezone: America/New_York
collections:
  herboristerie:
    title: Herboristerie
    output: false
    order:
      - pour-quels-maux-consulter.markdown
      - efficacite-des-plantes-medicinales.markdown
      - pourquoi-consulter-une-herboriste-naturopathe.markdown
      - deroulement-dune-consultation.markdown
  massages:
    title: Massages
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
  source_dir: _sass
