---
title: elianelemieux.ca
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: chrisrhymes/bulma-clean-theme
theme_color: rgb(146, 159, 133)
